### ISSUE TITLE
Unable to check 409 response status from getFiles

### ISSUE THREAD

**Issue by markkimsal** [hellosign/hellosign-php-sdk#111]
The API documentation mentions that calling signature_request/files/[requestid] may return 409 if the signed PDFs are not available yet.

There doesn't seem to be a way to get the status as client->getFiles() swallows up the guzzle response, and the rest call response is only the getBody() portion.

The closest I can think is to try
```php
$client->rest->getStatus();
```
or 
```php
$client->checkStatus();
```
But both of these solutions are blocked by protected status.

**Comment by hazemhamedhs** [comment]
Hi @markkimsal 

This is Hazem from API support.

Have you tried using [getSignatureRequest](https://github.com/hellosign/hellosign-php-sdk#checking-the-status-of-a-signature-request) function to get the current status for each signer. Also, we highly recommend user to take advantage of our [callbacks](https://app.hellosign.com/api/eventsAndCallbacksWalkthrough) and wait for the **signature_request_all_signed** event to POST before downloading the signed document using the Get Files endpoint. This callback event fires off once everyone has signed and the document is ready for download.

If you need any further help, please feel free to send a ticket to apisupport@hellosign.com.
