### ISSUE TITLE
Can you please tag a new release?

### ISSUE THREAD

**Issue by jackwh** [hellosign/hellosign-php-sdk#113]
Support for Guzzle v7.0 was added to `composer.json` in September 2020, but there's not been a tagged release since then. I'm using Guzzle 7 in my project (it's a requirement for Laravel v8), and am currently unable to update this package beyond v3.4.3.

Thanks in advance!

**Comment by schmoove** [comment]
@algorozco could we please have a new release tagged ASAP? This is causing a lot of guzzle issues with other packages. Thank you!

**Comment by algorozco** [comment]
Hey @schmoove, I'm no longer part of the HelloSign org so I'm unable to help with this, unfortunately. I'd suggest that you reach out to apisupport@hellosign.com to have their team review. Good luck!

**Comment by IanSimpson** [comment]
A +1 for this. I have dependency conflicts cropping up - up-to-date libraries which require Guzzle 7, which creates difficulties for me.

**Comment by schmoove** [comment]
i've sent a request to HelloSign support, and apparently it has been triaged to the relevant team member.

**Comment by OnionKnightN** [comment]
Thank you for this. We are having this reviewed internally and will report back as soon as possible.

**Comment by jspaetzel** [comment]
Tagged a new release, 3.7.0
