### ISSUE TITLE
Shwoing Fatal error: Uncaught HelloSign\Error: [unknown] Unknown error thrown in 

### ISSUE THREAD

**Issue by bhaveshvaghela32** [hellosign/hellosign-php-sdk#12]
I did below code 
$client = new HelloSign\Client('df754dd564e52fb2891a60eb2fea777b5320397b82c207***********');
$request = new HelloSign\SignatureRequest;
$request->enableTestMode();
$request->setTitle('NDA with Acme Co.');
$request->setSubject('The NDA we talked about');
$request->setMessage('Please sign this NDA and then we can discuss more. Let me know if you have any questions.');
$request->addSigner(new HelloSign\Signer(array(
    'name' => 'Bhavesh',
    'email_address' => 'bhaveshvaghela32@gmail.com',
    'order' => 1
)));
$request->addFile('mpdf.pdf');
$response = $client->sendSignatureRequest($request);

$client = new HelloSign\Client('df754dd564e52fb2891a60eb2fea777b5320397b82c20729b984081ebc530bb6');
$request = new HelloSign\SignatureRequest;
$request->enableTestMode();
$request->setTitle('NDA with Acme Co.');
$request->setSubject('The NDA we talked about');
$request->setMessage('Please sign this NDA and then we can discuss more. Let me know if you have any questions.');
$request->addSigner(new HelloSign\Signer(array(
    'name' => 'Bhavesh',
    'email_address' => 'bhaveshvaghela32@gmail.com',
    'order' => 1
)));
$response = $client->sendSignatureRequest($request);
When i run above code i give error as 

Fatal error: Uncaught HelloSign\Error: [unknown] Unknown error thrown in (my folder path)

**Comment by cmpaul** [comment]
It might be this line:

``` php
$request->addFile('mpdf.pdf');
```

You may want to confirm that the path is accessible to your application code from the path that it's running. What do you get when you run, prior to that code:

``` php
if (file_exists('mpdf.pdf')) { echo "File found"; } else { echo "FILE NOT FOUND"; }
```

**Comment by bhaveshvaghela32** [comment]
Yes cmpaul , there was issue with path , i replaced $request->addFile('mpdf.pdf'); with $request->addFile(**DIR** . '/mpdf.pdf'); so it works now. error solved , Thank you cmpaul.
