### ISSUE TITLE
How do I set page number for form fields placement in setFormFieldsPerDocument?

### ISSUE THREAD

**Issue by jayeshinho** [hellosign/hellosign-php-sdk#15]
I would like to add form fields for signature on the second page of my PDF. How do I add it in setFormFieldsPerDocument options? I set "page" : 2 but it does not work.

**Comment by BHSPitMonkey** [comment]
Y-coordinates are cumulative, and page dimensions are 680x880. The top of
page 2 is just past the bottom of page 1.

If you need more assistance, feel free to reach out to us at:
apisupport@hellosign.com

**Comment by jayeshinho** [comment]
Thank you very much.
