### ISSUE TITLE
User reports validation types do not work when sending a signature request with the PHP SDK

### ISSUE THREAD

**Issue by johnnycupcakes** [hellosign/hellosign-php-sdk#19]
"We have started using the Validation Types but it appears they have no affect. Alphabetical fields still accept numerals, SSN fields accept less than 9 digits, etc. 

$embedded_request = new HelloSign\EmbeddedSignatureRequest($request, $client_id); 
try { 
$response = $client->createEmbeddedSignatureRequest($embedded_request);

But I see the uxVersion is supported there also:

public function createEmbeddedSignatureRequest(EmbeddedSignatureRequest $request, $ux_version = null)

$request = new HelloSign\TemplateSignatureRequest; 
$request->setTemplateId(...) 
$request->setSubject(...); 
$request->setMessage(...); 
$request->setSigner(...); 
$request->setCustomFieldValue(...);

$embedded_request = new HelloSign\EmbeddedSignatureRequest($request, $client_id); 
try { 
$response = $client->createEmbeddedSignatureRequest($embedded_request,2); // UX version 2

The Validation Types are still not enforced. The Labels in our templates are still not pre-filled when used in multiple forms."

**Comment by desmondw** [comment]
As discussed with @johnnycupcakes there does not appear to be an issue with this functionality and logically if there was an issue it would most likely be tied to the HelloSign application directly rather than this SDK.
