### ISSUE TITLE
Add Editable Merge Fields support

### ISSUE THREAD

**Issue by rmelencio** [hellosign/hellosign-php-sdk#20]
When updating the SDKs to include editable merge fields, please also update the SDK git repos README examples (if necessary) and the following in the API docs:
- "Send with Template" endpoint example
- "Send Embedded Signature Request with Template" endpoint example
- Templates Walkthrough
- Signature Request Walkthrough -> Using Templates

**Comment by desmondw** [comment]
Implemented.
