### ISSUE TITLE
Add support for API App endpoints

### ISSUE THREAD

**Issue by garnold** [hellosign/hellosign-php-sdk#25]
We need to be able to create and update [API apps](https://www.hellosign.com/api/reference#ApiApp) via the PHP SDK.

**Comment by rmelencio** [comment]
Hi @garnold ,

You can create and update API apps in the Settings page on HelloSign.com.  This is good if you have just a few apps.

Are you creating/updating a large number of API apps?

-Ronald

**Comment by garnold** [comment]
Hi @rmelencio , thanks for the quick response!  A few thoughts:
- We try to automate everything for repeatability and to eliminate user error, and generally try to avoid password sharing (unfortunately our Gold Plan doesn't afford us multiple users to the web UI).
- Perhaps a bit pedantic, but in my opinion an SDK should reflect the complete API, not just selected pieces.
- Most importantly, we have multiple developers working on our app, using Ngrok to open tunnels for testing HelloSign API callbacks.  Our current approach requires us to manually define API Apps for each developer, and update the callback URLs for those API Apps whenever Ngrok is restarted to reflect the new subdomain.  It'd be ideal to be able to script these updates.

Hope that helps.

**Comment by desmondw** [comment]
@garnold I agree with you that it would be ideal to have the SDK up-to-date on all changes, but considering the number of SDKs we support it's more practical to make updates on a case-by-case basis or await pull requests. ;_;

I'd be interested in understanding why your flow requires you to work like this. Regarding your callback issue, I've only used ngrok a couple of times but it looks like it supports the ability to create static tunnel urls: https://ngrok.com/docs#http

**Comment by garnold** [comment]
@desmondw Thanks for the response.  Named domains are only part of paid Ngrok.  

However, Alex@apisupport pointed out that we can create individual free HelloSign accounts for each developer and use the existing Account API endpoints to change the callback URLs.  I'm going to try this option now.

**Comment by radhack** [comment]
Make sure to include the White Labeling options in the /update endpoint

**Comment by radhack** [comment]
This issue can be closed @cmpaul or @BHSPitMonkey - Jen is building this out as part of issue #58

**Comment by cmpaul** [comment]
Thanks @radhack
