### ISSUE TITLE
`HelloSign\SignatureRequest` does not support `client_id` parameter

### ISSUE THREAD

**Issue by garnold** [hellosign/hellosign-php-sdk#26]
This makes testing callbacks in an isolated environment impossible.

https://www.hellosign.com/api/reference#SignatureRequest

**Comment by garnold** [comment]
I was able to work around this issue by creating a custom subclass of `HelloSign\SignatureRequest`:

``` php
namespace HelloSign;

class SignatureRequestExt extends SignatureRequest {

    protected $client_id = null;

    public function setClientId($client_id) {
        $this->client_id = $client_id;
        return $this;
    }
}
```

Still, this parameter should be supported in your official SDK.

**Comment by BHSPitMonkey** [comment]
Hi @garnold,

Sorry for the inconvenience, and thanks for sharing your workaround. The ability to assign a client_id to non-embedded signature requests is actually a relatively recent change to our API, and the client libraries just haven't all caught up yet I'm afraid. We'll try to ship a new version as soon as we can.

**Comment by garnold** [comment]
Sounds good, thanks @BHSPitMonkey

**Comment by desmondw** [comment]
Implemented.

**Comment by garnold** [comment]
Thanks @desmondw !
