### ISSUE TITLE
editing template issues

### ISSUE THREAD

**Issue by yurii-zhukow** [hellosign/hellosign-php-sdk#29]
1. when entering label name cannot use arrow keys on keyboard
2. when changing validation rule - label wiped out
3. cannot zoom in editing document to adjust input area rect
4. field alignment would be appreciated. mostly centered text over the field

**Comment by renderf0x** [comment]
Heya @yurii-zhukow -

These aren't related to the PHP SDK per se, but are some valid UX feedback for the editor.

I'll pass these along to Product here and have them consider for the embedded editor page.
