### ISSUE TITLE
[bad_request] Invalid parameter: file

### ISSUE THREAD

**Issue by itsazzad** [hellosign/hellosign-php-sdk#3]
Can you please help me that why I am getting this error?
Fatal error: Uncaught HelloSign\Error: [bad_request] Invalid parameter: file thrown in /.../vendor/hellosign/hellosign-php-sdk/library/HelloSign/Client.php on line 740

I am using like this:  $request->addFile('nda.pdf');

**Comment by BHSPitMonkey** [comment]
We have just pushed an update to correct this. Please use composer's `update` command or checkout the latest revision and it should work.

**Comment by chocolatethunder** [comment]
This issue is still not fixed. Please re-open!
