### ISSUE TITLE
Add support for new parameters in "list" api calls

### ISSUE THREAD

**Issue by radhack** [hellosign/hellosign-php-sdk#32]
Would be nice to be able to return more than the default of 20 results in the getSignatureRequests call.

**Comment by desmondw** [comment]
Thanks for your input @radhack - our wrappers are not always up to date with our endpoints so thanks for pointing this out.

We'd want to update (as far as I can see):
- page_size
- query
- account_id (for list templates)

**Comment by jyoung488** [comment]
Resolved in #75
