### ISSUE TITLE
Warning class does not extend BaseException

### ISSUE THREAD

**Issue by nater540** [hellosign/hellosign-php-sdk#35]
It appears that the `Warning` class does not extend from `BaseException`, however it is being treated as an exception and thrown from this line:
https://github.com/HelloFax/hellosign-php-sdk/blob/v3/library/HelloSign/Client.php#L906

In PHP7 and above this will generate the following error
`Cannot throw objects that do not implement Throwable`

**Comment by desmondw** [comment]
Thanks for bringing this to our attention @nater540 . We will queue this for investigation, but feel free to address the issue with a pull request of your own if you wish.

**Comment by jeffgrove** [comment]
I have a branch created for this but I don't have permissions to push to origin. Any suggestions? I suppose I need to become a contributor? Thanks in advance.

**Comment by desmondw** [comment]
@jeffgrove You'll need to make a pull request against our primary branch. When we have time we'll review it and provide feedback or integrate your changes. Thanks for contributing!

**Comment by jeffgrove** [comment]
@desmondw @nater540 
Created a pull request. Not sure if I did it right. This is my first foray into open source.
