### ISSUE TITLE
Cannot use embedded signing with embedded requesting with template

### ISSUE THREAD

**Issue by radhack** [hellosign/hellosign-php-sdk#45]
Here's the documentation on how to include setEmbeddedSigning():

```
$client = new HelloSign\Client('api_key_here');
$client_id = 'YOUR_CLIENT_ID';

$templateId = $previouslySavedTemplate->getId();

$baseReq = new HelloSign\TemplateSignatureRequest();
$baseReq->setTemplateId($templateId);
$baseReq->setSigner('Signer', 'jack@example.com', 'Jack');
$baseReq->setSigningRedirectUrl('http://example.com/signing');
$baseReq->setRequestingRedirectUrl('http://example.com/requesting');
$baseReq->setRequesterEmailAddress('jill@example.com');
$baseReq->addMetadata('custom_id', '1234');

$request = new HelloSign\EmbeddedSignatureRequest($baseReq);
$request->setClientId($client_id);
$request->enableTestMode();
$request->setEmbeddedSigning();

$response = $client->createUnclaimedDraftEmbeddedWithTemplate($request);
```

That doesn't work though, as we remove the is_for_embedded_signing param from [EmbeddedSignatureRequest.php on line 59](https://github.com/HelloFax/hellosign-php-sdk/blob/v3/library/HelloSign/EmbeddedSignatureRequest.php#L59).

To fix this, change AbstractSignatureRequestWrapper:
- remove static default for [is_for_embedded_signing](https://github.com/HelloFax/hellosign-php-sdk/blob/v3/library/HelloSign/AbstractSignatureRequestWrapper.php#L52) (hellosign's default is false, no need to duplicate in SDK)

and change EmbeddedSignatureRequest:
- remove the exception for 'is_for_embedded_signing', since it's not included unless set by including setEmbeddedSigning() explicitly.

**Comment by desmondw** [comment]
@radhack would you mind making a pull request to merge this functionality in?

**Comment by radhack** [comment]
@desmondw code changes are ready for review sir. https://github.com/HelloFax/hellosign-php-sdk/pull/46
