### ISSUE TITLE
getMetadata function does not work (re-open of issue #2)

### ISSUE THREAD

**Issue by ghost** [hellosign/hellosign-php-sdk#5]
``` php
public function getMetadata($key) {
        if (is_array($this->metadata)) {
            return (isset($this->metadata[$key])) ? $this->metadata[$key] : null;
        }
        return null;
    }
```

`$this->metadata` is always an object so the function will always return null. Unless I'm understanding incorrectly, the library either needs to:

1) convert the metadata object to an array OR 
2) the getMetadata function needs to access the $key as an object instead of an array.

**Comment by cmpaul** [comment]
I've made a quick change that should ensure this object is always an assoc. array. Can you give this a shot again and let me know if you're still having trouble accessing keys?
