### ISSUE TITLE
EmbeddedSignatureRequest 500: No recipients specified

### ISSUE THREAD

**Issue by netpoe** [hellosign/hellosign-php-sdk#52]
Hi. I'm following the [Embedded Photo Release](https://app.hellosign.com/api/embeddedSigningExample) example from the API Docs with HelloSign PHP SDK version: `"hellosign/hellosign-php-sdk": "3.*@dev"`: 

```php
public function getEmbeddedSignatureRequestAction()
    {
        $client = new \HelloSign\Client(self::HELLO_SIGN_API_KEY);
        $request = new \HelloSign\TemplateSignatureRequest;
        $request->enableTestMode();
        $request->setTemplateId(self::SINGLE_SIGNATURE_TEMPLATE_ID);
        $request->setSubject('Carta de autorización para consulta de buró de crédito');
        $request->setMessage('Mensaje');
        $request->addSigner('subject', 'mail@email.com', 'Subject');
        $request->addMetadata(self::SINGLE_SIGNATURE_TEMPLATE_FIELDS['folio_de_usuario'], 'u123');

        $clientId = self::HELLO_SIGN_CLIENT_ID;
        $embeddedRequest = new \HelloSign\EmbeddedSignatureRequest($request, $clientId);
        $response = $client->createEmbeddedSignatureRequest($embeddedRequest, 2);
    }
```

However, I'm getting a 500 error: `No recipients specified` from line 903 of `/app/vendor/hellosign/hellosign-php-sdk/library/HelloSign/Client.php:903`:

```
stdClass Object
(
    [error] => stdClass Object
        (
            [error_msg] => No recipients specified
            [error_name] => bad_request
        )

)
```

The params sent to the `createEmbeddedSignatureRequest` method of the Client are these: 

```
Array
(
    [template_ids] => Array
        (
            [0] => xxx
        )

    [ccs] => Array
        (
        )

    [signers] => Array
        (
            [subject] => Array
                (
                    [name] => Name
                    [email_address] => mail@email.com
                )

        )

    [metadata] => Array
        (
            [8d7689_9] => u123
        )

    [warnings] => Array
        (
        )

    [test_mode] => 1
    [subject] => Subject
    [message] => Mensaje
    [file] => Array
        (
        )

    [file_url] => Array
        (
        )

    [client_id] => xxx
)
```

Aren't the signers the recipients?

I've tried with the `addSigner` method with no success.

**Comment by jeffgrove** [comment]
Looks like a param order issue. Here is the addSigner API that I'm using (lifted from AbstractSignatureRequest.php).

    /**
     * Adds a signer to the signature request
     *
     * @param  mixed $email_or_signer
     * @param  string $name
     * @param  string $index
     * @return AbstractSignatureRequest
     */
    public function addSigner($email_or_signer, $name = null, $index = null)

**Comment by netpoe** [comment]
@jeffgrove thanks for the quick reply. 

I've also tried these methods: 

```
$request->setSigner('subject', 'mail@email.com', 'Gus');
$request->addSigner('mail@email.com', 'Gus', 1);
$request->addSigner(new \HelloSign\Signer(array(
    'name' => 'Gus',
    'email_address' => 'mail@email.com',
    'order' => 1
)));
```

and I'm getting the same response

**Comment by jeffgrove** [comment]
@netpoe Weird. I was able to get the embedded signatures to work in our prototype but our first phase release that we shipped a couple months ago does not use embedded yet so I'm far from an expert. I have to run off to a meeting. If I can find the prototype that I got working, I'll send it to you. It will take me a few hours and I may not it. Good luck!

**Comment by jeffgrove** [comment]
@netpoe I checked the prototype I have. It is exactly like the no template sample. The only difference from your code (other than the template) is that I do not specify a 2nd param for $ux_version, I leave that param as the default.

**Comment by netpoe** [comment]
@jeffgrove uhm. I've tried without specifying the ux_version as well. 

Are you using the `"hellosign/hellosign-php-sdk": "3.*@dev"` too?

**Comment by jeffgrove** [comment]
@netpoe Yes, we are using "hellosign/hellosign-php-sdk": "3.*@dev" though we have made a feature request to Hello Sign to remove the @dev since we have a production system depending on this and our developers get nervous if they see @dev components in the production composer.json. I'm running on OSX w/ PHP 5.6.30 though that doesn't seem like it matters.

**Comment by jeffgrove** [comment]
@netpoe At this point, I'd suggest you contact Hello Sign support directly. They have always been quick to respond to my questions. In this case, if you have an issue directly with their sample/walkthrough code, I would think they would want to know and would be helpful.

**Comment by netpoe** [comment]
@jeffgrove I've submitted the issue to HelloSign support. Again, thanks for your time and effort. Very much appreciated.

**Comment by netpoe** [comment]
There is definitively something wrong with the API. I'm getting the same response by using pure cURL: 

```php
public static function getEmbeddedSignatureUrl()
    {
        $data = [
            'client_id' => self::HELLO_SIGN_CLIENT_ID,
            'template_id' => self::SINGLE_SIGNATURE_TEMPLATE_ID,
            'subject' => 'My First embedded signature request with a reusable form',
            'message' => 'Awesome, right?',
            'signers' => [
                'Client' => [
                    'email_address' => 'mail@email.com',
                    'name' => 'Name'
                ]
            ],
            'test_mode' => 1,
        ];

        $ch = curl_init('https://api.hellosign.com/v3/signature_request/create_embedded_with_template');

        curl_setopt($ch, CURLOPT_USERNAME, self::HELLO_SIGN_API_KEY);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($data));

        $response = curl_exec($ch);

        if (curl_errno($ch)) {
            throw new \Exception(curl_error($ch));
        }

        curl_close($ch);

        print_r($response); exit;
    }
```

Response: 

```
{"error":{"error_msg":"No recipients specified","error_name":"bad_request"}}
```

**Comment by BHSPitMonkey** [comment]
Hi Gus,

Are you sure "Client" is the exact name of the signer role on that template? You can verify this by opening the Template in the web UI, or by calling `GET /v3/template/:id` and looking at the `signer_roles` array in the JSON response.

**Comment by kevincompton** [comment]
I am also getting the same issue, I insured that the name of the signer is "Client"

**Comment by netpoe** [comment]
Hi @kevincompton I ended up using pure cURL but maybe it works for you as well: 

```php
public static function getEmbeddedSignatureRequest()
{
    $env = getenv('ENV');

    $data = [
        'client_id' => ($env == 'prod') ? self::HELLO_SIGN_CLIENT_ID : self::HELLO_SIGN_CLIENT_ID_DEV,
        'template_id' => self::SINGLE_SIGNATURE_TEMPLATE_ID,
        'subject' => 'Subject',
        'message' => '',
        'signers' => [
            'Client' => [
                'email_address' => $user->email,
                'name' => $user->NAME
            ]
        ],
        'custom_fields' => json_encode([
            [
                'name' => 'field_label',
                'value' => $value
            ],
        ])
    ];

    if ($env != 'prod') {
        $data['test_mode'] = 1;
    }

    $ch = curl_init('https://api.hellosign.com/v3/signature_request/create_embedded_with_template');

    $apiKey = ($env == 'prod') ? self::HELLO_SIGN_API_KEY : self::HELLO_SIGN_API_KEY_DEV;

    curl_setopt($ch, CURLOPT_USERNAME, $apiKey);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($data));

    if (curl_errno($ch)) {
        throw new \Exception(curl_error($ch));
    }

    $response = json_decode(curl_exec($ch));

    if (array_key_exists('error', $response)) {
        throw new \Exception($response->error->error_msg);
    }

    curl_close($ch);

    return $response;
}
```

**Comment by psanchez54** [comment]
the error doesn't give us any clue, but in my case the issue got fixed after using the same exact Role set in the Template for the signer
$request->addSigner('ROLENAME', 'mail@email.com', 'Subject');

**Comment by jyoung488** [comment]
@netpoe Closing this issue, but feel free to write into apisupport@hellosign.com if you run into any additional errors!

**Comment by bassamanator** [comment]
I'm getting the same error when I try to `create_embedded_with_template` via Postman. Adding `signers` key to `Client` (which I get from `signer_roles` array) isn't helping. 

Am I doing something wrong?

(Running in test_mode 1)
