### ISSUE TITLE
Vendor must be not in git repo

### ISSUE THREAD

**Issue by Bukashk0zzz** [hellosign/hellosign-php-sdk#53]
Why you add libraries to repository? This not correct for many reasons. 
Do you have any reason for this?

This makes PHPStorm feel sad.

**Comment by reedmaniac** [comment]
I also just noticed this when my Sublime definitions popup used your PHPUnit directory opposed to the top level one in the vendor directory.

**Comment by coffe4u** [comment]
I agree, there are a number of reasons that the vendor directory should not be committed to this git repo.

**Comment by nathanbuchar** [comment]
Ah yes, this is very wrong. I'll send this through the appropriate channels

Edit: Whoops didn't mean to mark it as closed

**Comment by jyoung488** [comment]
Resolved in #76
