### ISSUE TITLE
Null fields in getAccount() response object

### ISSUE THREAD

**Issue by Framinus** [hellosign/hellosign-php-sdk#78]
Calls to getAccount() are returning null values for templates_left, api_signature_requests_left and documents_left. Calls to the exact same user account using the Httpful library to return a raw http request are returning with these values intact.

Raw request response:
![image](https://user-images.githubusercontent.com/24632499/46547859-28c36d80-c882-11e8-92dc-1d45a84f9aea.png)

SDK response:
![image](https://user-images.githubusercontent.com/24632499/46547905-514b6780-c882-11e8-9c05-eee2a4b3f4cc.png)

**Comment by jyoung488** [comment]
@Framinus thanks! i'll address this 😃
