### ISSUE TITLE
addFileUrl fails with unClaimedDraft type request

### ISSUE THREAD

**Issue by oliviermills** [hellosign/hellosign-php-sdk#8]
Using S3 signed public link e.g. `https://s3.amazonaws.com/...../file.pdf?AWSAccessKeyId=1234&Expires=1433474924&Signature=12345`

The exact same file works fine with the same code, using `addFile()`.

**Comment by desmondw** [comment]
@oliviermills I have been unable to duplicate this issue, even using an s3 link. Perhaps your link was expired when you used it? If you're still able to reproduce this, please reply with some code examples and the response / failure you see.
