### ISSUE TITLE
What is the requester email address?

### ISSUE THREAD

**Issue by ryanmortier** [hellosign/hellosign-php-sdk#83]
Ref: https://github.com/hellosign/hellosign-php-sdk/blob/4e4793ae95f6c47e9ed8ac57738d5333d5076060/library/HelloSign/AbstractSignatureRequest.php#L241-L245

What is the difference between just adding a signer with `addSigner()` vs setting a requester email? It doesn't seem to be required but what does it do exactly?

**Comment by jyoung488** [comment]
@ryanmortier The addSigner() method sets the signer of the document or whoever needs to complete it. The requester is the individual requesting the document to be signed.

**Comment by ryanmortier** [comment]
@jyoung488 What happens if I don't set the requester email? For example if I add two signers but don't set a requester email?

Thanks.

**Comment by jyoung488** [comment]
@ryanmortier This option is only allowed in certain cases anyway. The requester is the individual sending the signature request and it is based on the API key used. If you need further clarification, please feel free to write into apisupport@hellosign.com with your questions.
