### ISSUE TITLE
Add function deactivateAllowAddCCs

### ISSUE THREAD

**Issue by dimsamaras** [hellosign/hellosign-php-sdk#87]
in the Template class the function deactivateAllowAddCCs is missing (as desctribed in the API reference guide: https://app.hellosign.com/api/reference#create_embedded_template_draft)
Similar call to $templateRequest->disableAllowReassign(); and $templateRequest->disableAllowDecline();

**Comment by Framinus** [comment]
To clarify, the allow_ccs parameter needs to be added to the following endpoints so that this feature can be enabled or disabled:

Send Signature Request with Template & Send Embedded Signature Request with Template

**Comment by dimsamaras** [comment]
It needs to be be hidden when the template is created in the first place!

Στις Τετ, 23 Ιαν 2019 στις 8:08 μ.μ., ο/η James <notifications@github.com>
έγραψε:
