### ISSUE TITLE
Add ability to configure HTTP / Guzzle Client

### ISSUE THREAD

**Issue by nrutman** [hellosign/hellosign-php-sdk#90]
I am using the HelloSign SDK and realized it lacks the ability to send its requests through a web proxy. Since it utilizes Guzzle under the hood, this is easily achievable by accepting a set of Guzzle options at instantiation.

I have included a PR that does this (https://github.com/hellosign/hellosign-php-sdk/pull/89).

 As an added benefit, this gives developers additional access to configure the underlying HTTP (Guzzle) client according to their use case. For example, I think this would also satisfy https://github.com/hellosign/hellosign-php-sdk/pull/65.

**Comment by algorozco** [comment]
Hi Nate! Sorry we didn't get back to you before, PR #89 was merged some time ago. Please let us know if you are facing any issues.

API Support Team

**Comment by nrutman** [comment]
Hi @algorozco. Yes, I saw that it was merged some time ago and we've been using it. Thanks for the follow-up!
