### ISSUE TITLE
Facebook Advert issue with SDK?

### ISSUE THREAD

**Issue by MTELtd** [hellosign/hellosign-php-sdk#94]
Hello,

We deployed HS to one of our domains and the moment the new WordPress plugin was installed to the site, FaceBook 'disallowed' the domain for advertising on the basis that it breached their "community guidelines". They will not give us any additional information, but the moment the plugin was deleted we were able to get the domain approved again.

The only clue we have is that the use of Eval() can be considered suspicious and this statement appears in several files in the SDK.

Do you think this could be the issue? If so, is there any alternative?

Thanks, Ian

**Comment by algorozco** [comment]
Hi Ian,

Apologies we missed this before. For help with troubleshooting it works better if you contact to us at apisupport@hellosign.com. Could you please reach out there if you are still experiencing any issues?

API Support Team

**Comment by MTELtd** [comment]
Hello,

The documentation directed me to post this on Github ... so I did.

The issue is resolved now, thank you.

Kind regards,
Ian
