### ISSUE TITLE
Download signature document

### ISSUE THREAD

**Issue by yonatonreid** [hellosign/hellosign-php-sdk#95]
How do i go about downloading a signature document?

**Comment by algorozco** [comment]
Hi Yonaton,

You can do that using the "client->getFiles();" method, sending the signature request ID related to the document as a parameter. The response will include a file_url (with an expiration time) that you can hit to download the file. 

This is an example of the use:
```
$apikey = "API_KEY";
$client = new HelloSign\Client($apikey);
$signature_request_id='658a7741e1e8aae2912471e57a64a38085578d71'

$response = $client->getFiles($signature_request_id);
$file_url = $response->getFileUrl();
echo $url;
```
In this case I'm simply printing the URL in console but you could use a cURL or your preferred method to download the file.

Hope this helps! If there are further questions, please email us at apisupport@hellosign.com. 

Thanks,
Ana
